# Generated by Django 5.2.12 on 2026-03-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, help_text='e.g. gpt-4o, gemini-1.5-pro', max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before showing to users')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanation', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'AI Explanation',
                'verbose_name_plural': 'AI Explanations',
            },
        ),
    ]
